server:
  port: 8092

springdoc:
  swagger-ui:
    enabled: true
    path: swagger-ui.html

jwt:
  secret-key: CestL9uDpUserUseCasermHHcnV7VNyFjnUGkAZTqQVYBGdBETbmqwJmt2xgSgy8rG2p65m95F6EG5CQ9TBjCBScLsQJY3XQ2p5yGQEsxGZP7gdLZaKUYTGFgjZEMB7gX3tQaSHQY4GmJCjzSd5dCbdCrNhryP6WvDT5mHrsE2F4f4nHxSPef3jY7LcyT72dqPgxhy5ZEeJEPGNSykQpjCyKNhAS7Vu9mRT2XCshch3FwSjBDwzMK8P2s2UDanLCHarcERhAJ4s

twilio:
  account-sid: AC08c58450018c11e9158d0fccb08749af
  auth-token: 29660323ddaca062d4cb6e4e52c927b9
  phone: +18143348092